version: "3.7"
services:
  app:
    build: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
      - cache
  cache:
    image: redis:6.0.8
    container_name: cache
  db:
    image: mongo:4.4.5
    container_name: db
    environment:
      MONGO_INITDB_DATABASE: malware
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init.js
